name = "out"
defaultTargets = ["Out"]
moreLeanArgs = ["--tstack=400000"]

[[lean_lib]]
name = "Out"
leanOptions.weak.linter.style.nameCheck = false
moreLeancArgs= ["-fbracket-depth=500"]

[[require]]
name = "Sail"
git = "https://github.com/rems-project/lean-sail"
rev = "archsem-lean"