name: Build Sail Tiny ARM For Lean

on:
  workflow_dispatch:

env:
  OPAMVERBOSE: 1

jobs:
  build:
    strategy:
      matrix:
        version: [5.2.1]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: System dependencies
      run: |
        apt update
        apt install -y build-essential pkg-config libgmp-dev z3 cvc4 opam curl bash wget

    - name: Checkout SAIL
      run: |
        #git clone https://github.com/rems-project/sail.git
        # TODO: Move to mainline sail when it gets merged in
        git clone https://github.com/ineol/sail.git
        (cd sail ; git checkout ineol/push-npmxwlqwxxur)

    - name: Restore cached opam
      id: cache-opam-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.opam
        key: ${{ matrix.os }}-${{ matrix.version }}

    - name: Setup opam
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      run: |
        opam init --yes --no-setup --shell=sh --compiler=${{ matrix.version }}
        opam update --yes
        opam upgrade --yes

    - name: Install Sail dependences
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      run: |
        eval $(opam env)
        (cd sail; opam install sail --deps-only --yes)

    - name: Save cached opam
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      id: cache-opam-save
      uses: actions/cache/save@v4
      with:
        path: ~/.opam
        key: ${{ steps.cache-opam-restore.outputs.cache-primary-key }}

    - name: Install Sail
      run: |
        eval $(opam env)
        (cd sail; make install)

    - name: Build the Sail Tiny Arm Model for Lean
      run: |
        git clone https://github.com/rems-project/sail-tiny-arm.git
        cd sail-tiny-arm
        # TODO: update to latest sail-tiny-arm when its working.
        git checkout 8f17b71497fa2e4f8b275194989b6dbbc55dc97e
        eval $(opam config env)
        make lean
        cd ..

    - name: Restore cached lake directory
      id: cache-lake-restore
      uses: actions/cache/restore@v4
      with:
        path: sail-tiny-arm/lean-snapshot/out/.lake
        key: ${{ matrix.os }}-${{ matrix.version }}


    - name: Install elan
      run: |
        wget https://elan.lean-lang.org/elan-init.sh
        bash elan-init.sh -y

    - name: Use Lean to build the model and record errors
      id: run-lake
      run: |
        source ~/.profile
        cd sail-tiny-arm/lean-snapshot/out
        lake update
        lake build | tee build_log.txt
        cd ../../..

    - name: Save cached lake
      id: cache-lake-save
      uses: actions/cache/save@v4
      with:
        path: sail-tiny-arm/lean-snapshot/out/.lake
        key: ${{ steps.cache-lake-restore.outputs.cache-primary-key }}

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: main
        FOLDER: sail-tiny-arm/lean-snapshot/out
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_DIR: .

